/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import dao.VentaDAO;

/**
 *
 * @author USUARIO
 */
public class FARMACEUTICO extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(FARMACEUTICO.class.getName());
    pVentasFac pventas = new pVentasFac();
    CardLayout vista;

    public FARMACEUTICO() {
        initComponents();

        this.setExtendedState(FARMACEUTICO.MAXIMIZED_BOTH);
        java.awt.GraphicsEnvironment env
                = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());

        vista = (CardLayout) piniciofarma.getLayout();

        icono_formulario();
    }

    public void icono_formulario() {
        URL url = getClass().getResource("/imagenes/ICONO_SISTEMA.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piniciofarma = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        aa = new javax.swing.JMenu();
        mrventaf = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        maperturaf = new javax.swing.JMenuItem();
        mcierref = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO AL SISTEMA DE CONTROL COMERCIAL");
        setBackground(new java.awt.Color(255, 255, 255));

        piniciofarma.setBackground(new java.awt.Color(255, 255, 255));
        piniciofarma.setLayout(new java.awt.CardLayout());
        piniciofarma.add(jLabel1, "card2");

        jMenuBar1.setBorder(null);
        jMenuBar1.setOpaque(true);

        aa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/venta.png"))); // NOI18N
        aa.setText("VENTAS");
        aa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aa.addActionListener(this::aaActionPerformed);

        mrventaf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mrventaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/regventa.png"))); // NOI18N
        mrventaf.setText("REGISTRAR VENTA");
        mrventaf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mrventaf.addActionListener(this::mrventafActionPerformed);
        aa.add(mrventaf);

        jMenuBar1.add(aa);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/caja.png"))); // NOI18N
        jMenu2.setText("CAJA");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        maperturaf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maperturaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/apertura.png"))); // NOI18N
        maperturaf.setText("APERTURA");
        maperturaf.addActionListener(this::maperturafActionPerformed);
        jMenu2.add(maperturaf);

        mcierref.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mcierref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cierre.png"))); // NOI18N
        mcierref.setText("CIERRE");
        mcierref.addActionListener(this::mcierrefActionPerformed);
        jMenu2.add(mcierref);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(piniciofarma, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(piniciofarma, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed

    }//GEN-LAST:event_aaActionPerformed

    private void mcierrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcierrefActionPerformed
        pcierre panelcierre = new pcierre();
        piniciofarma.add(panelcierre, "cierre caja");
        vista.show(piniciofarma, "cierre caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mcierrefActionPerformed

    private void maperturafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maperturafActionPerformed
        papertura panelapertura = new papertura();
        piniciofarma.add(panelapertura, "aperturar caja");
        vista.show(piniciofarma, "aperturar caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_maperturafActionPerformed

    private void mrventafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrventafActionPerformed
        dao.CajaDAO cajaDAO = new dao.CajaDAO();
        modelo.Caja cajaActiva = cajaDAO.obtenerCajaActiva(modelo.Sesion.getIdUsuario());

        if (cajaActiva == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe aperturar SU caja antes de registrar ventas.",
                    "Caja cerrada", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        piniciofarma.add(pventas, "registrar venta");
        vista.show(piniciofarma, "registrar venta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mrventafActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FARMACEUTICO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem maperturaf;
    private javax.swing.JMenuItem mcierref;
    private javax.swing.JMenuItem mrventaf;
    private javax.swing.JPanel piniciofarma;
    // End of variables declaration//GEN-END:variables
}
