/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author USUARIO
 */
public class INICIO_ADMIN extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INICIO_ADMIN.class.getName());

    /**
     * Creates new form INICIO_ADMIN
     */
    pkardexinv pkardexinv = new pkardexinv();
    palmacen palmacen = new palmacen();
    pVentasFac pventas = new pVentasFac();
    pmercaderia panelmercaderia = new pmercaderia();
    proles panelusuarios = new proles();
    ptrabajadores paneltrabajadores = new ptrabajadores();
    putilidades panelutilidades = new putilidades();
    pranking prankingproductos = new pranking();
    CardLayout vista;

    private int idUsuarioLogueado;
    private String nombreUsuarioLogueado;

    public INICIO_ADMIN() {
        initComponents();
        this.setExtendedState(INICIO_ADMIN.MAXIMIZED_BOTH);
        java.awt.GraphicsEnvironment env = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        vista = (CardLayout) pinicioadmin.getLayout();
        icono_formulario();
    }

    public void icono_formulario() {
        URL url = getClass().getResource("/imagenes/ICONO_SISTEMA.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    private ImageIcon cargarIcono(String ruta) {
        URL url = getClass().getResource(ruta);
        if (url != null) {
            return new ImageIcon(url);
        } else {
            System.err.println("Imagen no encontrada: " + ruta);
            return new ImageIcon(); // Icono vacío como fallback
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pinicioadmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cusuarios = new javax.swing.JMenu();
        mtrabajadores = new javax.swing.JMenuItem();
        musuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cmercaderia = new javax.swing.JMenu();
        ming_producto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        calmacen = new javax.swing.JMenu();
        ming_almacen = new javax.swing.JMenuItem();
        mkardex = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cventas = new javax.swing.JMenu();
        mreg_venta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ccaja = new javax.swing.JMenu();
        mc_apertura = new javax.swing.JMenuItem();
        mc_cierre = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        creportes = new javax.swing.JMenu();
        m_utilidades = new javax.swing.JMenuItem();
        ran_product = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO AL SISTEMA DE CONTROL COMERCIAL");

        pinicioadmin.setBackground(new java.awt.Color(255, 255, 255));
        pinicioadmin.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/logo.png"))); // NOI18N
        pinicioadmin.add(jLabel1, "card2");

        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jMenuBar1.setOpaque(true);

        cusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/seguridad.png"))); // NOI18N
        cusuarios.setText("SEGURIDAD");
        cusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cusuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mtrabajadores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mtrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/trabajador.png"))); // NOI18N
        mtrabajadores.setText("TRABAJADORES");
        mtrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mtrabajadores.addActionListener(this::mtrabajadoresActionPerformed);
        cusuarios.add(mtrabajadores);

        musuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        musuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuario.png"))); // NOI18N
        musuarios.setText("USUARIOS");
        musuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musuarios.addActionListener(this::musuariosActionPerformed);
        cusuarios.add(musuarios);

        jMenuBar1.add(cusuarios);

        jMenu1.setEnabled(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(16, 8));
        jMenuBar1.add(jMenu1);

        cmercaderia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/mercaderia.png"))); // NOI18N
        cmercaderia.setText("MERCADERIA");
        cmercaderia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmercaderia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ming_producto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ming_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/crearprod.png"))); // NOI18N
        ming_producto.setText("CREAR PRODUCTO");
        ming_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ming_producto.addActionListener(this::ming_productoActionPerformed);
        cmercaderia.add(ming_producto);

        jMenuBar1.add(cmercaderia);

        jMenu2.setEnabled(false);
        jMenu2.setPreferredSize(new java.awt.Dimension(16, 10));
        jMenuBar1.add(jMenu2);

        calmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/almacen.png"))); // NOI18N
        calmacen.setText("ALMACEN");
        calmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calmacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ming_almacen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ming_almacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ingalmacen.png"))); // NOI18N
        ming_almacen.setText("INGRESO ALMACEN");
        ming_almacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ming_almacen.addActionListener(this::ming_almacenActionPerformed);
        calmacen.add(ming_almacen);

        mkardex.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mkardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/kardex.png"))); // NOI18N
        mkardex.setText("KARDEX");
        mkardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mkardex.addActionListener(this::mkardexActionPerformed);
        calmacen.add(mkardex);

        jMenuBar1.add(calmacen);

        jMenu3.setEnabled(false);
        jMenu3.setPreferredSize(new java.awt.Dimension(16, 10));
        jMenuBar1.add(jMenu3);

        cventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/venta.png"))); // NOI18N
        cventas.setText("VENTAS");
        cventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mreg_venta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mreg_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/regventa.png"))); // NOI18N
        mreg_venta.setText("REGISTRAR VENTA");
        mreg_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mreg_venta.addActionListener(this::mreg_ventaActionPerformed);
        cventas.add(mreg_venta);

        jMenuBar1.add(cventas);

        jMenu4.setEnabled(false);
        jMenu4.setPreferredSize(new java.awt.Dimension(16, 10));
        jMenuBar1.add(jMenu4);

        ccaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/caja.png"))); // NOI18N
        ccaja.setText("CAJA");
        ccaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ccaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mc_apertura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mc_apertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/apertura.png"))); // NOI18N
        mc_apertura.setText("APERTURA");
        mc_apertura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mc_apertura.addActionListener(this::mc_aperturaActionPerformed);
        ccaja.add(mc_apertura);

        mc_cierre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mc_cierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cierre.png"))); // NOI18N
        mc_cierre.setText("CIERRE");
        mc_cierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mc_cierre.addActionListener(this::mc_cierreActionPerformed);
        ccaja.add(mc_cierre);

        jMenuBar1.add(ccaja);

        jMenu5.setEnabled(false);
        jMenu5.setPreferredSize(new java.awt.Dimension(16, 10));
        jMenuBar1.add(jMenu5);

        creportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reportes.png"))); // NOI18N
        creportes.setText("REPORTES");
        creportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creportes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        m_utilidades.setText("UTILIDADES");
        m_utilidades.addActionListener(this::m_utilidadesActionPerformed);
        creportes.add(m_utilidades);

        ran_product.setText("RANKING PRODUCTOS");
        ran_product.addActionListener(this::ran_productActionPerformed);
        creportes.add(ran_product);

        jMenuBar1.add(creportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pinicioadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pinicioadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtrabajadoresActionPerformed
        pinicioadmin.add(paneltrabajadores, "adm Trabajadores");
        vista.show(pinicioadmin, "adm Trabajadores");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mtrabajadoresActionPerformed

    private void musuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musuariosActionPerformed
        panelusuarios.cargarCombos();
        pinicioadmin.add(panelusuarios, "adm USUARIOS");
        vista.show(pinicioadmin, "adm USUARIOS");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_musuariosActionPerformed

    private void ming_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ming_productoActionPerformed
        pinicioadmin.add(panelmercaderia, "ingresar mercaderia");
        vista.show(pinicioadmin, "ingresar mercaderia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_ming_productoActionPerformed

    private void mc_aperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc_aperturaActionPerformed
        papertura panelapertura = new papertura();
        pinicioadmin.add(panelapertura, "aperturar caja");
        vista.show(pinicioadmin, "aperturar caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mc_aperturaActionPerformed

    private void mc_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc_cierreActionPerformed
        pcierre panelcierre = new pcierre();
        pinicioadmin.add(panelcierre, "cierre caja");
        vista.show(pinicioadmin, "cierre caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mc_cierreActionPerformed

    private void ming_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ming_almacenActionPerformed
        pinicioadmin.add(palmacen, "ingreso mercaderia");
        vista.show(pinicioadmin, "ingreso mercaderia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_ming_almacenActionPerformed

    private void mreg_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mreg_ventaActionPerformed
        pinicioadmin.add(pventas, "registrar venta");
        vista.show(pinicioadmin, "registrar venta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mreg_ventaActionPerformed

    private void mkardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkardexActionPerformed
        pinicioadmin.add(pkardexinv, "historial inventario");
        vista.show(pinicioadmin, "historial inventario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mkardexActionPerformed

    private void m_utilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_utilidadesActionPerformed
        pinicioadmin.add(panelutilidades, "calculo utitlidades");
        vista.show(pinicioadmin, "calculo utitlidades");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_m_utilidadesActionPerformed

    private void ran_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ran_productActionPerformed
        pinicioadmin.add(prankingproductos, "ranqueando productos");
        vista.show(pinicioadmin, "ranqueando productos");
        prankingproductos.cargarGraficoRanking(); // refresca con datos actuales de la BD
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_ran_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INICIO_ADMIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu calmacen;
    private javax.swing.JMenu ccaja;
    private javax.swing.JMenu cmercaderia;
    private javax.swing.JMenu creportes;
    private javax.swing.JMenu cusuarios;
    private javax.swing.JMenu cventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem m_utilidades;
    private javax.swing.JMenuItem mc_apertura;
    private javax.swing.JMenuItem mc_cierre;
    private javax.swing.JMenuItem ming_almacen;
    private javax.swing.JMenuItem ming_producto;
    private javax.swing.JMenuItem mkardex;
    private javax.swing.JMenuItem mreg_venta;
    private javax.swing.JMenuItem mtrabajadores;
    private javax.swing.JMenuItem musuarios;
    private javax.swing.JPanel pinicioadmin;
    private javax.swing.JMenuItem ran_product;
    // End of variables declaration//GEN-END:variables
}
