/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author USUARIO
 */
public class INICIO_ADMIN extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INICIO_ADMIN.class.getName());

    /**
     * Creates new form INICIO_ADMIN
     */
    
    pkardexinv pkardexinv = new pkardexinv();
    palmacen palmacen = new palmacen();
    pVentasFac pventas = new pVentasFac();
    pcierre panelcierre = new pcierre();
    papertura panelapertura = new papertura();
    pmercaderia panelmercaderia = new pmercaderia();
    proles panelusuarios = new proles();
    ptrabajadores paneltrabajadores = new ptrabajadores();
    CardLayout vista;

    public INICIO_ADMIN() {
        initComponents();
        this.setExtendedState(INICIO_ADMIN.MAXIMIZED_BOTH);
        java.awt.GraphicsEnvironment env = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        vista = (CardLayout) pinicioadmin.getLayout();
        icono_formulario();
    }

    public void icono_formulario() {
        URL url = getClass().getResource("/imagenes/ICONO_SISTEMA.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pinicioadmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cusuarios = new javax.swing.JMenu();
        mtrabajadores = new javax.swing.JMenuItem();
        musuarios = new javax.swing.JMenuItem();
        cmercaderia = new javax.swing.JMenu();
        ming_producto = new javax.swing.JMenuItem();
        calmacen = new javax.swing.JMenu();
        ming_almacen = new javax.swing.JMenuItem();
        mkardex = new javax.swing.JMenuItem();
        cventas = new javax.swing.JMenu();
        mreg_venta = new javax.swing.JMenuItem();
        ccaja = new javax.swing.JMenu();
        mc_apertura = new javax.swing.JMenuItem();
        mc_cierre = new javax.swing.JMenuItem();
        creportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO AL SISTEMA DE CONTROL COMERCIAL");

        pinicioadmin.setBackground(new java.awt.Color(255, 255, 255));
        pinicioadmin.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8072883 (1).png"))); // NOI18N
        pinicioadmin.add(jLabel1, "card2");

        cusuarios.setText("SEGURIDAD");

        mtrabajadores.setText("TRABAJADORES");
        mtrabajadores.addActionListener(this::mtrabajadoresActionPerformed);
        cusuarios.add(mtrabajadores);

        musuarios.setText("USUARIOS");
        musuarios.addActionListener(this::musuariosActionPerformed);
        cusuarios.add(musuarios);

        jMenuBar1.add(cusuarios);

        cmercaderia.setText("MERCADERIA");

        ming_producto.setText("INGRESO PRODUCTO");
        ming_producto.addActionListener(this::ming_productoActionPerformed);
        cmercaderia.add(ming_producto);

        jMenuBar1.add(cmercaderia);

        calmacen.setText("ALMACEN");

        ming_almacen.setText("INGRESO ALMACEN");
        ming_almacen.addActionListener(this::ming_almacenActionPerformed);
        calmacen.add(ming_almacen);

        mkardex.setText("KARDEX");
        mkardex.addActionListener(this::mkardexActionPerformed);
        calmacen.add(mkardex);

        jMenuBar1.add(calmacen);

        cventas.setText("VENTAS");

        mreg_venta.setText("REGISTRAR VENTA");
        mreg_venta.addActionListener(this::mreg_ventaActionPerformed);
        cventas.add(mreg_venta);

        jMenuBar1.add(cventas);

        ccaja.setText("CAJA");

        mc_apertura.setText("APERTURA");
        mc_apertura.addActionListener(this::mc_aperturaActionPerformed);
        ccaja.add(mc_apertura);

        mc_cierre.setText("CIERRE");
        mc_cierre.addActionListener(this::mc_cierreActionPerformed);
        ccaja.add(mc_cierre);

        jMenuBar1.add(ccaja);

        creportes.setText("REPORTES");
        jMenuBar1.add(creportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pinicioadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pinicioadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtrabajadoresActionPerformed
        pinicioadmin.add(paneltrabajadores, "adm Trabajadores");
        vista.show(pinicioadmin, "adm Trabajadores");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mtrabajadoresActionPerformed

    private void musuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musuariosActionPerformed
         panelusuarios.cargarCombos();
        pinicioadmin.add(panelusuarios, "adm USUARIOS");
        vista.show(pinicioadmin, "adm USUARIOS");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_musuariosActionPerformed

    private void ming_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ming_productoActionPerformed
        pinicioadmin.add(panelmercaderia, "ingresar mercaderia");
        vista.show(pinicioadmin, "ingresar mercaderia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_ming_productoActionPerformed

    private void mc_aperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc_aperturaActionPerformed
        pinicioadmin.add(panelapertura, "aperturar caja");
        vista.show(pinicioadmin, "aperturar caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mc_aperturaActionPerformed

    private void mc_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mc_cierreActionPerformed
        pinicioadmin.add(panelcierre, "cierre caja");
        vista.show(pinicioadmin, "cierre caja");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mc_cierreActionPerformed

    private void ming_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ming_almacenActionPerformed
        pinicioadmin.add(palmacen, "ingreso mercaderia");
        vista.show(pinicioadmin, "ingreso mercaderia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_ming_almacenActionPerformed

    private void mreg_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mreg_ventaActionPerformed
        pinicioadmin.add(pventas, "registrar venta");
        vista.show(pinicioadmin, "registrar venta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mreg_ventaActionPerformed

    private void mkardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkardexActionPerformed
        pinicioadmin.add(pkardexinv, "historial inventario");
        vista.show(pinicioadmin, "historial inventario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_mkardexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INICIO_ADMIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu calmacen;
    private javax.swing.JMenu ccaja;
    private javax.swing.JMenu cmercaderia;
    private javax.swing.JMenu creportes;
    private javax.swing.JMenu cusuarios;
    private javax.swing.JMenu cventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mc_apertura;
    private javax.swing.JMenuItem mc_cierre;
    private javax.swing.JMenuItem ming_almacen;
    private javax.swing.JMenuItem ming_producto;
    private javax.swing.JMenuItem mkardex;
    private javax.swing.JMenuItem mreg_venta;
    private javax.swing.JMenuItem mtrabajadores;
    private javax.swing.JMenuItem musuarios;
    private javax.swing.JPanel pinicioadmin;
    // End of variables declaration//GEN-END:variables
}
