/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import conexion.ConexioDB;

/**
 *
 * @author Usuario
 */
public class palmacen extends javax.swing.JPanel {

    DefaultTableModel modeloAlmacen;

    /**
     * Creates new form PanelMercaderia
     */
    public palmacen() {
        initComponents();
        configurarTablaAlmacen();
        inicializarFilaVacia();
    }

    public void configurarTablaAlmacen() {
        String[] titulos = {"CÓDIGO DE BARRAS", "DESCRIPCIÓN", "CANTIDAD", "ID"};

        modeloAlmacen = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Solo dejamos editar el Código de Barras (0) y la Cantidad (2)
                return column == 0 || column == 2;
            }
        };
        talmacen_ingreso.setModel(modeloAlmacen);

        // Ocultar la columna ID (índice 3) para procesamiento interno en base de datos
        talmacen_ingreso.getColumnModel().getColumn(3).setMinWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(3).setMaxWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(3).setPreferredWidth(0);

        // Listener para buscar el producto automáticamente cuando se digite el código de barras
        modeloAlmacen.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();

                // Si los cambios ocurrieron en la columna 0 ("CÓDIGO DE BARRAS")
                if (column == 0) {
                    Object cbObj = modeloAlmacen.getValueAt(row, 0);
                    if (cbObj != null && !cbObj.toString().trim().isEmpty()) {
                        buscarProductoPorCodigo(cbObj.toString().trim(), row);
                    }
                }
            }
        });
    }

    private void inicializarFilaVacia() {
        if (modeloAlmacen != null) {
            modeloAlmacen.addRow(new Object[]{"", "", "", ""});
        }
    }

    private void buscarProductoPorCodigo(String codigo, int fila) {
        String sql = "SELECT Id_producto, descripcion FROM PRODUCTO WHERE codigo_barras = ?";

        try (Connection con = ConexioDB.getConexion(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, codigo);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int idProd = rs.getInt("Id_producto");
                    String desc = rs.getString("descripcion");

                    // Usamos invokeLater para prevenir excepciones de concurrencia e hilos en Swing
                    java.awt.EventQueue.invokeLater(() -> {
                        modeloAlmacen.setValueAt(desc, fila, 1);   // Inserta descripción hallada
                        modeloAlmacen.setValueAt(idProd, fila, 3); // Inserta ID del producto
                        modeloAlmacen.setValueAt("1", fila, 2);    // Sugiere cantidad base de 1
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "El código de barras '" + codigo + "' no existe en el sistema.", "Producto no encontrado", JOptionPane.WARNING_MESSAGE);
                    java.awt.EventQueue.invokeLater(() -> {
                        modeloAlmacen.setValueAt("", fila, 0); // revierte el texto inválido
                    });
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos al buscar producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbTipoMovimiento = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        talmacen_ingreso = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(808, 609));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(985, 985));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Movimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        cbTipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AJUSTE", "INVENTARIO POR PRODUCTO" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cbTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        talmacen_ingreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(talmacen_ingreso);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(btnguardar)
                        .addGap(122, 122, 122))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(btnguardar)))
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton6.setText("CERRAR");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        btnagregar.setText("+");
        btnagregar.addActionListener(this::btnagregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnagregar)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(234, 234, 234)
                .addComponent(btnagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java.awt.Container padre = this.getParent();

        if (padre != null) {
            padre.remove(this);

            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // Validar que la tabla contenga información procesable
        if (modeloAlmacen.getRowCount() == 0 || modeloAlmacen.getValueAt(0, 3).toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La tabla está vacía o no tiene productos válidos cargados.", "Datos insuficientes", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el tipo de movimiento seleccionado en el ComboBox
        String tipoMovimiento = cbTipoMovimiento.getSelectedItem().toString();

        Connection con = null;
        PreparedStatement psReset = null;
        PreparedStatement psUpdate = null;
        PreparedStatement psHistorial = null;

        try {
            con = ConexioDB.getConexion();
            con.setAutoCommit(false); // Transacción atómica segura

            // Definición de consultas SQL transaccionales
            String sqlReset = "UPDATE ALMACEN_STOCK SET stock_actual = 0 WHERE Id_producto = ?";

            String sqlUpdate = "MERGE INTO ALMACEN_STOCK AS Destino "
                    + "USING (SELECT ? AS Id_producto) AS Origen "
                    + "ON (Destino.Id_producto = Origen.Id_producto) "
                    + "WHEN MATCHED THEN "
                    + "    UPDATE SET stock_actual = Destino.stock_actual + ? "
                    + "WHEN NOT MATCHED THEN "
                    + "    INSERT (Id_producto, stock_actual) VALUES (Origen.Id_producto, ?);";

            String sqlHistorial = "INSERT INTO HISTORIAL_INVENTARIO (Id_producto, tipo_movimiento, cantidad, fecha_movimiento) VALUES (?, ?, ?, GETDATE())";

            psReset = con.prepareStatement(sqlReset);
            psUpdate = con.prepareStatement(sqlUpdate);
            psHistorial = con.prepareStatement(sqlHistorial);

            // --- PASO 1: Si es INVENTARIO POR PRODUCTO, borrón y cuenta nueva a 0 de los ítems en lista ---
            if (tipoMovimiento.equalsIgnoreCase("Inventario por Producto")) {
                for (int i = 0; i < modeloAlmacen.getRowCount(); i++) {
                    if (modeloAlmacen.getValueAt(i, 3) != null && !modeloAlmacen.getValueAt(i, 3).toString().isEmpty()) {
                        int idProd = Integer.parseInt(modeloAlmacen.getValueAt(i, 3).toString());
                        psReset.setInt(1, idProd);
                        psReset.addBatch();
                    }
                }
                psReset.executeBatch();
            }

            // --- PASO 2: Inyección de stock y generación de Kárdex/Historial ---
            for (int i = 0; i < modeloAlmacen.getRowCount(); i++) {
                if (modeloAlmacen.getValueAt(i, 3) == null || modeloAlmacen.getValueAt(i, 3).toString().isEmpty()
                        || modeloAlmacen.getValueAt(i, 2) == null || modeloAlmacen.getValueAt(i, 2).toString().isEmpty()) {
                    continue; // Ignora filas que se encuentren incompletas
                }

                int idProd = Integer.parseInt(modeloAlmacen.getValueAt(i, 3).toString());
                int cantidad = Integer.parseInt(modeloAlmacen.getValueAt(i, 2).toString());

                if (cantidad <= 0) {
                    con.rollback(); // Cancela la operación completa ante inconsistencias
                    JOptionPane.showMessageDialog(this, "Error en fila " + (i + 1) + ": La cantidad de ingreso debe ser mayor a 0.", "Valor inválido", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Parámetros de actualización de Stock
                psUpdate.setInt(1, idProd);
                psUpdate.setInt(2, cantidad);
                psUpdate.setInt(3, cantidad);
                psUpdate.addBatch();

                // Parámetros de Auditoría/Historial
                psHistorial.setInt(1, idProd);
                psHistorial.setString(2, tipoMovimiento.toUpperCase());
                psHistorial.setInt(3, cantidad);
                psHistorial.addBatch();
            }

            // Ejecución por bloques de comandos (Batch processing)
            psUpdate.executeBatch();
            psHistorial.executeBatch();

            con.commit(); // Todo se guardó correctamente sin fallos
            JOptionPane.showMessageDialog(this, "¡Movimiento de Almacén (" + tipoMovimiento + ") procesado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Reestructuración y reinicio limpio de la interfaz gráfica
            modeloAlmacen.setRowCount(0);
            inicializarFilaVacia();

        } catch (SQLException e) {
            if (con != null) {
                try {
                    con.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(this, "Error crítico al procesar el ingreso de almacén: " + e.getMessage(), "Error de Transacción", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (psReset != null) {
                    psReset.close();
                }
                if (psUpdate != null) {
                    psUpdate.close();
                }
                if (psHistorial != null) {
                    psHistorial.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        modeloAlmacen.addRow(new Object[]{"", "", "", ""});
    }//GEN-LAST:event_btnagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbTipoMovimiento;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable talmacen_ingreso;
    // End of variables declaration//GEN-END:variables
}
