/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import dao.AlmacenDAO;

/**
 *
 * @author Usuario
 */
public class palmacen extends javax.swing.JPanel {

    private AlmacenDAO almacenDAO = new AlmacenDAO();

    DefaultTableModel modeloAlmacen;

    /**
     * Creates new form PanelMercaderia
     */
    public palmacen() {
        initComponents();
        configurarTablaAlmacen();
        inicializarFilaVacia();
    }

    public void configurarTablaAlmacen() {
        String[] titulos = {"CÓDIGO DE BARRAS", "DESCRIPCIÓN", "UNIDAD", "CANTIDAD", "MULTIPLO", "ID"};

        modeloAlmacen = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0 || column == 3;
            }
        };
        talmacen_ingreso.setModel(modeloAlmacen);

        // Ocultar MULTIPLO (col 4) e ID (col 5)
        talmacen_ingreso.getColumnModel().getColumn(4).setMinWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(4).setMaxWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(4).setPreferredWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(5).setMinWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(5).setMaxWidth(0);
        talmacen_ingreso.getColumnModel().getColumn(5).setPreferredWidth(0);

        modeloAlmacen.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                if (column == 0) {
                    Object cbObj = modeloAlmacen.getValueAt(row, 0);
                    if (cbObj != null && !cbObj.toString().trim().isEmpty()) {
                        buscarProductoPorCodigo(cbObj.toString().trim(), row);
                    }
                }
            }
        });
    }

    private void inicializarFilaVacia() {
        if (modeloAlmacen != null) {
            modeloAlmacen.addRow(new Object[]{"", "", "", "", "", ""});
        }
    }

    private void buscarProductoPorCodigo(String codigo, int fila) {
        List<Object[]> presentaciones = almacenDAO.buscarPresentacionesPorCodigo(codigo);

        if (presentaciones.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El código '" + codigo + "' no existe en el sistema.",
                    "Producto no encontrado", JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(() -> modeloAlmacen.setValueAt("", fila, 0));
            return;
        }

        Object[] presSeleccionada;
        if (presentaciones.size() == 1) {
            presSeleccionada = presentaciones.get(0);
        } else {
            String[] opciones = new String[presentaciones.size()];
            for (int i = 0; i < presentaciones.size(); i++) {
                Object[] p = presentaciones.get(i);
                opciones[i] = String.format("%s (x%d)", p[2], p[3]);
            }
            String seleccion = (String) JOptionPane.showInputDialog(this,
                    "Este producto tiene varias presentaciones.\nSeleccione la que está ingresando:",
                    "Seleccionar presentación", JOptionPane.QUESTION_MESSAGE,
                    null, opciones, opciones[0]);
            if (seleccion == null) {
                java.awt.EventQueue.invokeLater(() -> modeloAlmacen.setValueAt("", fila, 0));
                return;
            }
            presSeleccionada = presentaciones.get(java.util.Arrays.asList(opciones).indexOf(seleccion));
        }

        final Object[] pres = presSeleccionada;
        java.awt.EventQueue.invokeLater(() -> {
            modeloAlmacen.setValueAt(pres[1], fila, 1); // Descripción
            modeloAlmacen.setValueAt(pres[2], fila, 2); // Unidad
            modeloAlmacen.setValueAt(1, fila, 3); // Cantidad = 1
            modeloAlmacen.setValueAt(pres[3], fila, 4); // Multiplo (oculto)
            modeloAlmacen.setValueAt(pres[0], fila, 5); // Id_producto (oculto)
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talmacen_ingreso = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cbTipoMovimiento = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(808, 609));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(985, 985));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR MERCADERIA AL ALMACEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        talmacen_ingreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(talmacen_ingreso);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Movimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        cbTipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AJUSTE", "INVENTARIO POR PRODUCTO" }));
        cbTipoMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cbTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/mas.png"))); // NOI18N
        btnagregar.setBorder(null);
        btnagregar.setBorderPainted(false);
        btnagregar.setContentAreaFilled(false);
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregar.setFocusPainted(false);
        btnagregar.addActionListener(this::btnagregarActionPerformed);

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/menos.png"))); // NOI18N
        btneliminar.setBorder(null);
        btneliminar.setBorderPainted(false);
        btneliminar.setContentAreaFilled(false);
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setFocusPainted(false);
        btneliminar.addActionListener(this::btneliminarActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton6.setText("SALIR");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(this::jButton6ActionPerformed);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar.png"))); // NOI18N
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setFocusPainted(false);
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        btnmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscarprod.png"))); // NOI18N
        btnmostrar.setBorder(null);
        btnmostrar.setBorderPainted(false);
        btnmostrar.setContentAreaFilled(false);
        btnmostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmostrar.setFocusPainted(false);
        btnmostrar.addActionListener(this::btnmostrarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setText("BUSCAR PRODUCTO");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setText("GUARDAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)))
                .addGap(147, 147, 147)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnguardar)
                    .addComponent(btnmostrar)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java.awt.Container padre = this.getParent();

        if (padre != null) {
            padre.remove(this);

            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (modeloAlmacen.getRowCount() == 0
                || modeloAlmacen.getValueAt(0, 3) == null
                || modeloAlmacen.getValueAt(0, 3).toString().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La tabla está vacía o no tiene productos válidos.",
                    "Datos insuficientes", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tipoMovimiento = cbTipoMovimiento.getSelectedItem().toString();

        // Recoger solo las filas completas (que tengan Id_producto)
        List<Object[]> filas = new ArrayList<>();
        for (int i = 0; i < modeloAlmacen.getRowCount(); i++) {
            Object idObj = modeloAlmacen.getValueAt(i, 5);
            Object canObj = modeloAlmacen.getValueAt(i, 3);
            if (idObj == null || idObj.toString().isEmpty()) {
                continue;
            }
            if (canObj == null || canObj.toString().isEmpty()) {
                continue;
            }
            filas.add(new Object[]{
                modeloAlmacen.getValueAt(i, 0), // código barras
                modeloAlmacen.getValueAt(i, 1), // descripción
                modeloAlmacen.getValueAt(i, 2), // unidad
                modeloAlmacen.getValueAt(i, 3), // cantidad
                modeloAlmacen.getValueAt(i, 4), // multiplo
                modeloAlmacen.getValueAt(i, 5) // Id_producto
            });
        }

        if (filas.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay filas válidas para guardar.",
                    "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean exito = almacenDAO.guardarMovimientoStock(tipoMovimiento, filas);
        if (exito) {
            JOptionPane.showMessageDialog(this,
                    "¡Movimiento de Almacén (" + tipoMovimiento + ") procesado con éxito!",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            modeloAlmacen.setRowCount(0);
            inicializarFilaVacia();
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        modeloAlmacen.addRow(new Object[]{"", "", "", "", "", ""});
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        JDproducto dialog = new JDproducto(
                (java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setVisible(true);

        String codigo = dialog.getCodigoBarrasSeleccionado();
        if (codigo == null) {
            return;
        }

        // Buscar fila vacía
        int filaDestino = -1;
        for (int i = 0; i < modeloAlmacen.getRowCount(); i++) {
            Object val = modeloAlmacen.getValueAt(i, 0);
            if (val == null || val.toString().trim().isEmpty()) {
                filaDestino = i;
                break;
            }
        }
        if (filaDestino == -1) {
            modeloAlmacen.addRow(new Object[]{"", "", "", "", "", ""});
            filaDestino = modeloAlmacen.getRowCount() - 1;
        }

        // Escribir el código → el TableModelListener completa el resto
        modeloAlmacen.setValueAt(codigo, filaDestino, 0);
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int filaSeleccionada = talmacen_ingreso.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una fila para eliminar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // No permitir eliminar la fila vacía final
        Object idProd = modeloAlmacen.getValueAt(filaSeleccionada, 5);
        if (idProd == null || idProd.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar una fila vacía.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar: " + modeloAlmacen.getValueAt(filaSeleccionada, 1) + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmar == JOptionPane.YES_OPTION) {
            modeloAlmacen.removeRow(filaSeleccionada);
        }
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JComboBox<String> cbTipoMovimiento;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable talmacen_ingreso;
    // End of variables declaration//GEN-END:variables
}
