/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.ObjetoCombo;
import conexion.ConexioDB;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author USUARIO
 */
public class pmercaderia extends javax.swing.JPanel {

    /**
     * Creates new form pmercaderia
     */
    public pmercaderia() {
        initComponents();
        llenarCombo(cbMarca, "MARCA", "Id_marca", "nombre_marca");
        llenarCombo(cbPactivo, "PRINCIPIO_ACTIVO", "Id_principio", "nombre_principio");
        llenarCombo(cbConcentracion, "CONCENTRACION", "Id_concentracion", "valor_concentracion");
        llenarCombo(cbFfarma, "FORMA_FARMACEUTICA", "Id_forma", "nombre_forma");
        llenarCombo(cbCondventa, "CONDICION_VENTA", "Id_condicion", "nombre_condicion");
    }

    @SuppressWarnings("unchecked")
    public void llenarCombo(JComboBox combo, String tabla, String campoId, String campoNombre) {
        combo.removeAllItems();

        // 1. Agregamos una opción vacía al inicio
        combo.addItem(new ObjetoCombo(0, ""));

        String sql = "SELECT " + campoId + ", " + campoNombre + " FROM " + tabla + " ORDER BY " + campoNombre + " ASC";

        try (Connection con = ConexioDB.getConexion(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                int id = rs.getInt(campoId);
                String nombre = rs.getString(campoNombre);

                // Agregamos las instancias reales de la base de datos
                combo.addItem(new ObjetoCombo(id, nombre));
            }

            // para que el combo apunte a la opción vacía apenas cargue
            combo.setSelectedIndex(0);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al llenar combo " + tabla + ": " + e.getMessage());
        }
    }

    public void agregarNuevoElementoMaestro(JComboBox combo, String tabla, String columna, String tituloVentana) {
        String nuevoValor = JOptionPane.showInputDialog(this, "Ingrese el nuevo valor para " + tituloVentana + ":", tituloVentana, JOptionPane.QUESTION_MESSAGE);

        if (nuevoValor != null && !nuevoValor.trim().isEmpty()) {
            String sql = "INSERT INTO " + tabla + " (" + columna + ") VALUES (?)";

            try (Connection con = ConexioDB.getConexion(); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, nuevoValor.trim());
                ps.executeUpdate();

                // Refrescamos el combo usando tu función existente
                llenarCombo(combo, tabla, combo.getItemAt(0) != null ? "Id_" + columna.split("_")[1] : "Id", columna);

                // Seleccionamos el elemento recién creado
                for (int i = 0; i < combo.getItemCount(); i++) {
                    ObjetoCombo item = (ObjetoCombo) combo.getItemAt(i);
                    if (item.getNombre().equalsIgnoreCase(nuevoValor.trim())) {
                        combo.setSelectedIndex(i);
                        break;
                    }
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "El registro ya existe o hubo un error: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbCondventa = new javax.swing.JComboBox<>();
        btncventa = new javax.swing.JButton();
        txtFechaVencimiento = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbFfarma = new javax.swing.JComboBox<>();
        btnfarma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        cbPactivo = new javax.swing.JComboBox<>();
        cbConcentracion = new javax.swing.JComboBox<>();
        btnconcentracion = new javax.swing.JButton();
        btnpactivo = new javax.swing.JButton();
        btnagmarca = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtpcompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpventa = new javax.swing.JTextField();
        btnmostrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setText("CERRAR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jPanel3.setBackground(new java.awt.Color(239, 239, 239));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CREAR PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel2.setText("DESCRIPCION");

        jLabel9.setText("CODIGO");

        jLabel8.setText("CONDICION DE VENTA");

        cbCondventa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncventa.setText("+");
        btncventa.addActionListener(this::btncventaActionPerformed);

        txtFechaVencimiento.setModel(new javax.swing.SpinnerDateModel());

        jLabel7.setText("FECHA VENCIMIENTO");

        jLabel6.setText("FORMA FARMACEUTICA");

        cbFfarma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnfarma.setText("+");
        btnfarma.addActionListener(this::btnfarmaActionPerformed);

        jLabel3.setText("MARCA");

        jLabel4.setText("PRINCIPIO ACTIVO");

        jLabel5.setText("CONCENTRACION");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPactivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbConcentracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnconcentracion.setText("+");
        btnconcentracion.addActionListener(this::btnconcentracionActionPerformed);

        btnpactivo.setText("+");
        btnpactivo.addActionListener(this::btnpactivoActionPerformed);

        btnagmarca.setText("+");
        btnagmarca.addActionListener(this::btnagmarcaActionPerformed);

        btnguardar.setText("GUARDAR");
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        jLabel10.setText("PRECIO DE COMPRA");

        jLabel11.setText("PRECIO DE VENTA");

        btnmostrar.setText("MOSTRAR TODOS LOS PRODUCTOS");
        btnmostrar.addActionListener(this::btnmostrarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnguardar)
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbConcentracion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnconcentracion))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbPactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnpactivo))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnagmarca))))))
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpventa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(27, 27, 27)
                            .addComponent(cbCondventa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btncventa))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(cbFfarma, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnfarma))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagmarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnpactivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbConcentracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnconcentracion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbFfarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfarma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbCondventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncventa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtpcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtpventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnmostrar)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 266, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(66, 66, 66)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        java.awt.Container padre = this.getParent();

        if (padre != null) {
            padre.remove(this);

            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // 1. Validar que los ComboBox tengan una selección válida
        if (cbMarca.getSelectedItem() == null || ((ObjetoCombo) cbMarca.getSelectedItem()).getId() == 0
                || cbPactivo.getSelectedItem() == null || ((ObjetoCombo) cbPactivo.getSelectedItem()).getId() == 0
                || cbConcentracion.getSelectedItem() == null || ((ObjetoCombo) cbConcentracion.getSelectedItem()).getId() == 0
                || cbFfarma.getSelectedItem() == null || ((ObjetoCombo) cbFfarma.getSelectedItem()).getId() == 0
                || cbCondventa.getSelectedItem() == null || ((ObjetoCombo) cbCondventa.getSelectedItem()).getId() == 0) {

            JOptionPane.showMessageDialog(this, "Por favor, seleccione una opción válida en todos los campos desplegables.");
            return;
        }

        // 2. Extraer los objetos y sus IDs correctamente de cada combo
        ObjetoCombo marca = (ObjetoCombo) cbMarca.getSelectedItem();
        ObjetoCombo principio = (ObjetoCombo) cbPactivo.getSelectedItem();
        ObjetoCombo concentracion = (ObjetoCombo) cbConcentracion.getSelectedItem();
        ObjetoCombo forma = (ObjetoCombo) cbFfarma.getSelectedItem();
        ObjetoCombo condicion = (ObjetoCombo) cbCondventa.getSelectedItem();

        // 3. Capturar campos de texto y fecha 
        String descripcion = txtDescripcion.getText().trim();
        String codigoBarras = txtCodigoBarras.getText().trim();
        String preciocompra = txtpcompra.getText().trim();
        String precioventa = txtpventa.getText().trim();

        if (descripcion.isEmpty() || codigoBarras.isEmpty() || preciocompra.isEmpty() || precioventa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción y el código de barras son obligatorios.");
            return;
        }

        // Capturar la fecha desde el JSpinner
        java.util.Date fechaSeleccionada = (java.util.Date) txtFechaVencimiento.getValue();
        java.sql.Date fechaVencimiento = new java.sql.Date(fechaSeleccionada.getTime());

        // Validación opcional de fecha
        java.util.Date fechaHoy = new java.util.Date();
        if (fechaSeleccionada.before(fechaHoy)) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "La fecha seleccionada es anterior a hoy o ya venció. ¿Está seguro de que desea continuar?",
                    "Advertencia de Vencimiento", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (respuesta != JOptionPane.YES_OPTION) {
                return;
            }
        }

        // 4. Queries de Inserción
        String sqlProducto = "INSERT INTO PRODUCTO (codigo_barras, descripcion, Id_marca, Id_principio, Id_concentracion, Id_forma, fecha_vencimiento, Id_condicion, precio_venta, precio_compra) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        //NO LO USARE POR EL MOMENTO, String sqlPresentacion = "INSERT INTO PRODUCTO_PRESENTACION (Id_producto, medida, multiplo, aplica_igv, precio_venta) VALUES (?, ?, ?, ?, ?)";

        Connection con = null;
        PreparedStatement psProd = null;
        PreparedStatement psPres = null;

        try {
            con = ConexioDB.getConexion();
            con.setAutoCommit(false);

            // Guardar en la tabla maestro: PRODUCTO
            // Pedimos que nos devuelva el ID autogenerado (Id_producto)
            psProd = con.prepareStatement(sqlProducto, Statement.RETURN_GENERATED_KEYS);
            psProd.setString(1, codigoBarras);
            psProd.setString(2, descripcion);
            psProd.setInt(3, marca.getId());
            psProd.setInt(4, principio.getId());
            psProd.setInt(5, concentracion.getId());
            psProd.setInt(6, forma.getId());
            psProd.setDate(7, fechaVencimiento);
            psProd.setInt(8, condicion.getId());
            psProd.setString(9, precioventa);
            psProd.setString(10, preciocompra);

            psProd.executeUpdate();

            // Obtener el ID generado para el Producto
            int idProductoGenerado = 0;
            try (ResultSet rsKeys = psProd.getGeneratedKeys()) {
                if (rsKeys.next()) {
                    idProductoGenerado = rsKeys.getInt(1);
                }
            }

            con.commit();
            JOptionPane.showMessageDialog(this, "¡Medicamento registrado con éxito!");
            limpiarFormulario();

        } catch (SQLException e) {
            if (con != null) {
                try {
                    con.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                } // Cancela todo si hay error
            }
            JOptionPane.showMessageDialog(this, "Error al guardar el producto: " + e.getMessage());
        } finally {
            // Cerramos los recursos de manera segura
            try {
                if (psProd != null) {
                    psProd.close();
                }
                if (psPres != null) {
                    psPres.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed
    private void limpiarFormulario() {
        txtDescripcion.setText("");
        txtCodigoBarras.setText("");
        txtpventa.setText("");
        txtpcompra.setText("");

        // Al poner el índice en 0, regresarán a mostrar el campo vacío automáticamente
        if (cbMarca.getItemCount() > 0) {
            cbMarca.setSelectedIndex(0);
        }
        if (cbPactivo.getItemCount() > 0) {
            cbPactivo.setSelectedIndex(0);
        }
        if (cbConcentracion.getItemCount() > 0) {
            cbConcentracion.setSelectedIndex(0);
        }
        if (cbFfarma.getItemCount() > 0) {
            cbFfarma.setSelectedIndex(0);
        }
        if (cbCondventa.getItemCount() > 0) {
            cbCondventa.setSelectedIndex(0);
        }
    }
    private void btnagmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagmarcaActionPerformed
        agregarNuevoElementoMaestro(cbMarca, "MARCA", "nombre_marca", "Marca");
    }//GEN-LAST:event_btnagmarcaActionPerformed

    private void btnpactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpactivoActionPerformed
        agregarNuevoElementoMaestro(cbPactivo, "PRINCIPIO_ACTIVO", "nombre_principio", "Principio Activo");
    }//GEN-LAST:event_btnpactivoActionPerformed

    private void btnconcentracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconcentracionActionPerformed
        agregarNuevoElementoMaestro(cbConcentracion, "CONCENTRACION", "valor_concentracion", "Concentración");
    }//GEN-LAST:event_btnconcentracionActionPerformed

    private void btnfarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfarmaActionPerformed
        agregarNuevoElementoMaestro(cbFfarma, "FORMA_FARMACEUTICA", "nombre_forma", "Forma Farmacéutica");
    }//GEN-LAST:event_btnfarmaActionPerformed

    private void btncventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncventaActionPerformed
        agregarNuevoElementoMaestro(cbCondventa, "CONDICION_VENTA", "nombre_condicion", "Condición de Venta");
    }//GEN-LAST:event_btncventaActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        JDproducto dialogo = new JDproducto((Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_btnmostrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagmarca;
    private javax.swing.JButton btnconcentracion;
    private javax.swing.JButton btncventa;
    private javax.swing.JButton btnfarma;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnpactivo;
    private javax.swing.JComboBox<String> cbConcentracion;
    private javax.swing.JComboBox<String> cbCondventa;
    private javax.swing.JComboBox<String> cbFfarma;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbPactivo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JSpinner txtFechaVencimiento;
    private javax.swing.JTextField txtpcompra;
    private javax.swing.JTextField txtpventa;
    // End of variables declaration//GEN-END:variables
}
