/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.ProductoDAO;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class pranking extends javax.swing.JPanel {

    private final ProductoDAO dao = new ProductoDAO();

    /**
     * Creates new form pranking
     */
    public pranking() {
        initComponents();
        pmostrar_graficos.setLayout(new GridLayout(1, 2, 10, 10));
        cargarGraficoRanking();
    }

    public void cargarGraficoRanking() {
        pmostrar_graficos.removeAll();

        // ---- TOP 5 MÁS VENDIDOS ----
        DefaultCategoryDataset datasetMas = new DefaultCategoryDataset();
        List<Object[]> masVendidos = dao.obtenerTop5MasVendidos();
        for (Object[] fila : masVendidos) {
            datasetMas.addValue((Integer) fila[1], "Unidades", (String) fila[0]);
        }
        JFreeChart chartMas = ChartFactory.createBarChart(
                "Top 5 Más Vendidos", "Producto", "Unidades Vendidas",
                datasetMas, PlotOrientation.HORIZONTAL, false, true, false
        );
        colorearBarras(chartMas, new Color(46, 139, 87));

        // ---- TOP 5 MENOS VENDIDOS ----
        DefaultCategoryDataset datasetMenos = new DefaultCategoryDataset();
        List<Object[]> menosVendidos = dao.obtenerTop5MenosVendidos();
        for (Object[] fila : menosVendidos) {
            datasetMenos.addValue((Integer) fila[1], "Unidades", (String) fila[0]);
        }
        JFreeChart chartMenos = ChartFactory.createBarChart(
                "Top 5 Menos Vendidos", "Producto", "Unidades Vendidas",
                datasetMenos, PlotOrientation.HORIZONTAL, false, true, false
        );
        colorearBarras(chartMenos, new Color(178, 34, 34));

        ChartPanel cpMas = new ChartPanel(chartMas);
        ChartPanel cpMenos = new ChartPanel(chartMenos);

        pmostrar_graficos.add(cpMas);
        pmostrar_graficos.add(cpMenos);

        pmostrar_graficos.revalidate();
        pmostrar_graficos.repaint();
    }

    private void colorearBarras(JFreeChart chart, Color color) {
        CategoryPlot plot = chart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, color);
        plot.setBackgroundPaint(Color.WHITE);
        chart.setBackgroundPaint(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmostrar_graficos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pmostrar_graficosLayout = new javax.swing.GroupLayout(pmostrar_graficos);
        pmostrar_graficos.setLayout(pmostrar_graficosLayout);
        pmostrar_graficosLayout.setHorizontalGroup(
            pmostrar_graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        pmostrar_graficosLayout.setVerticalGroup(
            pmostrar_graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(this::btnsalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pmostrar_graficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pmostrar_graficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        java.awt.Container padre = this.getParent();

        if (padre != null) {
            padre.remove(this);

            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pmostrar_graficos;
    // End of variables declaration//GEN-END:variables
}
