/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.UsuarioDAO;
import modelo.Trabajador;
import modelo.Rol;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author USUARIO
 */
public class proles extends javax.swing.JPanel {

    /**
     * Creates new form proles
     */
    public proles() {
        initComponents();
        cargarCombos();
        cargarTabla();
        configurarSeleccionTabla();
        limpiarFormulario();
    }

    private int idUsuarioSeleccionado = -1;
    private boolean modoEdicion = false;

    public void cargarCombos() {
        UsuarioDAO dao = new UsuarioDAO();

        // Cargar Trabajadores sin usuario asignado
        cmbTrabajador.removeAllItems();
        for (modelo.Trabajador t : dao.obtenerTrabajadoresDisponibles()) {
            cmbTrabajador.addItem(t);
        }

        // Cargar Roles de la BD
        cmbRol.removeAllItems();
        for (modelo.Rol r : dao.obtenerRoles()) {
            cmbRol.addItem(r);
        }
    }

    //listar usuarios en tabla
    public void cargarTabla() {
        String[] columnas = {"ID", "Trabajador", "Nombre Usuario", "Rol", "Estado"};

        // Creamos el modelo
        DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        UsuarioDAO dao = new UsuarioDAO();
        ArrayList<Object[]> datos = dao.listarUsuariosParaTabla();

        for (Object[] fila : datos) {
            modeloTabla.addRow(fila);
        }

        // Ahora tblUsuarios ya será un JTable y reconocerá el método setModel
        tblUsuarios.setModel(modeloTabla);
        if (tblUsuarios.getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(80);
            tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(80);
        }
    }

    private void configurarSeleccionTabla() {
        tblUsuarios.getSelectionModel().addListSelectionListener(evt -> {
            if (evt.getValueIsAdjusting()) {
                return;
            }
            int fila = tblUsuarios.getSelectedRow();
            if (fila == -1) {
                return;
            }
            cargarDatosSeleccionados(fila);
        });
    }

    private void setCamposEditables(boolean editable) {
        txtUsuario.setEditable(editable);
        txtClave.setEditable(editable);
        cmbRol.setEnabled(editable);
    }

    private void cargarDatosSeleccionados(int fila) {
        idUsuarioSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
        String nombreUsuario = tblUsuarios.getValueAt(fila, 2).toString();
        String nombreRol = tblUsuarios.getValueAt(fila, 3).toString();
        String estadoActual = tblUsuarios.getValueAt(fila, 4).toString();

        txtUsuario.setText(nombreUsuario);
        txtClave.setText("");

        for (int i = 0; i < cmbRol.getItemCount(); i++) {
            Rol r = (Rol) cmbRol.getItemAt(i);
            if (r.getNombreRol().equalsIgnoreCase(nombreRol)) {
                cmbRol.setSelectedItem(r);
                break;
            }
        }

        setCamposEditables(false);
        cmbTrabajador.setEnabled(false);
        modoEdicion = false;

        btneditar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnguardar.setEnabled(false);

        // AHORA quedan bloqueados hasta presionar EDITAR
        btneliminar.setEnabled(false);
        btnEstado.setEnabled(false);
        btnEstado.setText(estadoActual.equalsIgnoreCase("Activo") ? "DESACTIVAR" : "ACTIVAR");
    }

    private void limpiarFormulario() {
        idUsuarioSeleccionado = -1;
        modoEdicion = false;

        txtUsuario.setText("");
        txtClave.setText("");
        if (cmbRol.getItemCount() > 0) {
            cmbRol.setSelectedIndex(0);
        }

        setCamposEditables(true);
        cmbTrabajador.setEnabled(true);

        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btncancelar.setEnabled(false);
        btnEstado.setEnabled(false);
        btnEstado.setText("DESACTIVAR");

        // AGREGAR esta línea
        btneliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        padmusuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTrabajador = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        btncerrar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tblusuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        padmusuarios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ADMINISTRAR USUARIOS");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CREAR USUARIO A TRABAJADOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel2.setText("TRABAJADOR");

        cmbTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("USUARIO");

        jLabel5.setText("CLAVE");

        jLabel6.setText("ROL");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncerrar.setText("CERRAR");
        btncerrar.addActionListener(this::btncerrarActionPerformed);

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(this::btneliminarActionPerformed);

        btneditar.setText("EDITAR");
        btneditar.addActionListener(this::btneditarActionPerformed);

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(this::btncancelarActionPerformed);

        btnEstado.setText("DESACTIVAR");
        btnEstado.addActionListener(this::btnEstadoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btneditar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(btneliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguardar)
                                    .addComponent(btncancelar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncerrar)
                                    .addComponent(btnEstado))
                                .addGap(62, 62, 62))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btncerrar)
                    .addComponent(btneliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditar)
                    .addComponent(btncancelar)
                    .addComponent(btnEstado))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblusuarios.setBackground(new java.awt.Color(255, 255, 255));
        tblusuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE USUARIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        tblusuarios.setForeground(new java.awt.Color(255, 255, 255));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblusuarios.setViewportView(tblUsuarios);

        javax.swing.GroupLayout padmusuariosLayout = new javax.swing.GroupLayout(padmusuarios);
        padmusuarios.setLayout(padmusuariosLayout);
        padmusuariosLayout.setHorizontalGroup(
            padmusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padmusuariosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(padmusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(padmusuariosLayout.createSequentialGroup()
                        .addComponent(tblusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        padmusuariosLayout.setVerticalGroup(
            padmusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padmusuariosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(padmusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(padmusuariosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addGroup(padmusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padmusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(padmusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        java.awt.Container padre = this.getParent();

        if (padre != null) {
            padre.remove(this);

            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (cmbRol.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol.");
            return;
        }

        String usuario = txtUsuario.getText().trim();
        String clave = new String(txtClave.getPassword()).trim();

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete el usuario.");
            return;
        }

        Rol rolSeleccionado = (Rol) cmbRol.getSelectedItem();
        int idRol = rolSeleccionado.getIdRol();
        UsuarioDAO dao = new UsuarioDAO();
        boolean exito;

        if (idUsuarioSeleccionado == -1) {
            // ---- NUEVO USUARIO ----
            if (cmbTrabajador.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un trabajador.");
                return;
            }
            if (clave.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete la contraseña.");
                return;
            }
            Trabajador trabSeleccionado = (Trabajador) cmbTrabajador.getSelectedItem();
            exito = dao.registrarUsuario(trabSeleccionado.getIdTrabajador(), usuario, clave, idRol);

            JOptionPane.showMessageDialog(this, exito
                    ? "¡Usuario asignado correctamente al trabajador!"
                    : "Error: El nombre de usuario ya existe en el sistema.");

        } else {
            // ---- EDICIÓN ----
            if (!modoEdicion) {
                JOptionPane.showMessageDialog(this, "Presione EDITAR antes de modificar los datos.");
                return;
            }
            exito = dao.actualizarUsuario(idUsuarioSeleccionado, usuario, clave, idRol);

            JOptionPane.showMessageDialog(this, exito
                    ? "¡Usuario actualizado correctamente!"
                    : "Error al actualizar. Verifique que el nombre de usuario no esté repetido.");
        }

        if (exito) {
            limpiarFormulario();
            cargarCombos();
            cargarTabla();
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // 1. Verificar si el usuario ha seleccionado una fila de la tabla
        int filaSeleccionada = tblUsuarios.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione el usuario que desea eliminar de la tabla.");
            return;
        }

        // 2. Obtener el ID del usuario desde la columna 0 de la fila seleccionada
        int idUsuario = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 0).toString());
        String nombreUsuario = tblUsuarios.getValueAt(filaSeleccionada, 2).toString();

        // 3. Confirmar la acción con el usuario mediante un cuadro de diálogo
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar al usuario '" + nombreUsuario + "'?",
                "Confirmar Eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        // 4. Si el usuario selecciona "SÍ", procedemos a borrarlo
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            UsuarioDAO dao = new UsuarioDAO();
            boolean exito = dao.eliminarUsuario(idUsuario);
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario eliminado con éxito!");
                cargarTabla();
                cargarCombos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo eliminar el usuario.\n\n"
                        + "Es posible que tenga ventas o cajas registradas.\n"
                        + "En ese caso, use el botón DESACTIVAR en su lugar.",
                        "No se pudo eliminar",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
        limpiarFormulario();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiarFormulario();
        tblUsuarios.clearSelection();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        if (idUsuarioSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla primero.");
            return;
        }

        boolean pasarAActivo = btnEstado.getText().equals("ACTIVAR");
        String accion = pasarAActivo ? "ACTIVAR" : "DESACTIVAR";

        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Desea " + accion + " al usuario '" + txtUsuario.getText() + "'?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }

        UsuarioDAO dao = new UsuarioDAO();
        boolean exito = dao.cambiarEstadoUsuario(idUsuarioSeleccionado, pasarAActivo);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Estado actualizado correctamente.");
            limpiarFormulario();
            cargarCombos();
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al cambiar el estado del usuario.");
        }
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        if (idUsuarioSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla primero.");
            return;
        }
        modoEdicion = true;
        setCamposEditables(true);
        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);

        // AHORA se habilitan aquí
        btneliminar.setEnabled(true);
        btnEstado.setEnabled(true);

        txtUsuario.requestFocus();
    }//GEN-LAST:event_btneditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<Object> cmbRol;
    private javax.swing.JComboBox<Object> cmbTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel padmusuarios;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JScrollPane tblusuarios;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
